[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:fastapi]
command=uvicorn credit_risk_engine.api.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:streamlit]
command=streamlit run credit_risk_engine/frontend/app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
